name: dedux
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  frappe: ^0.4.0
  option: ^1.1.0
dev_dependencies:
  browser: any
  react: any
