name: loop
description: An experimental unidirectional data flow framework for Dart
version: 0.0.1
author: Dan Schultz <schultz.t.dan@gmail.com>
homepage: https://github.com/danschultz/loop.dart
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  frappe: ^0.4.0
dev_dependencies:
  browser: any
  option: any
  react: any
